version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-intenciones
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tu_pass
      MYSQL_DATABASE: tu_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
